-- require('mobdebug').start()

VIRTUAL_WIDTH = 384
VIRTUAL_HEIGHT = 216

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

LEVEL_RENDER_OFFSET_TOP = 30
LEVEL_RENDER_OFFSET = 10

TILE_SIZE = 16

LINE_WIDTH = .5